/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui;

import com.connection.Koneksi;
import javax.swing.JFrame;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.awt.*;
import javax.swing.Action;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableColumnModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.tools.PDFBox;

/**
 *
 * @author LENOVO
 */
public class MainApp extends javax.swing.JFrame {
    
    private JButton btnTransaksiKey;
    public MainApp() {
    initComponents();
    updateLabelFaktur();
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
    txtKodeBarang.getDocument().addDocumentListener(new DocumentListener(){
        @Override
        public void insertUpdate(DocumentEvent e) {
           updateNamaBarang();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
           updateNamaBarang();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
           
        }
        
 
    
    });
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaKasir = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        faktur = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnLogout = new java.awt.Button();
        btnHapus = new java.awt.Button();
        btnTransaksi = new java.awt.Button();
        btnBayar = new java.awt.Button();
        btnTambah = new java.awt.Button();
        btnEdit = new java.awt.Button();
        btnClear = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalHarga1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHargaBarang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cariBarang1 = new java.awt.Button();
        jPanel7 = new javax.swing.JPanel();
        txtKembalian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(222, 20, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POINT OF SALES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(648, 648, 648)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(544, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(608, 118));

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("USER  :");

        namaKasir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(namaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaKasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(217, 217, 217));
        jPanel5.setMaximumSize(new java.awt.Dimension(582, 40));
        jPanel5.setPreferredSize(new java.awt.Dimension(582, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("FAKTUR :");
        jLabel3.setMaximumSize(new java.awt.Dimension(70, 40));
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 40));

        faktur.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faktur, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faktur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(222, 20, 20));
        jPanel6.setMaximumSize(new java.awt.Dimension(508, 180));
        jPanel6.setPreferredSize(new java.awt.Dimension(508, 180));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL RP.");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        txtTotalHarga.setBackground(new java.awt.Color(204, 204, 204));
        txtTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtTotalHarga.setForeground(new java.awt.Color(153, 255, 102));
        txtTotalHarga.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 165, Short.MAX_VALUE)
                .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(txtTotalHarga)
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLU", "Nama Barang", "Jumlah", "Harga", "Total Harga"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(153, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnLogout.setActionCommand("Logout");
        btnLogout.setBackground(new java.awt.Color(218, 7, 7));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setLabel("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(229, 35, 47));
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setLabel("Void");
        btnHapus.setPreferredSize(new java.awt.Dimension(130, 55));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(218, 7, 7));
        btnTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setLabel("Simpan");
        btnTransaksi.setPreferredSize(new java.awt.Dimension(130, 55));
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnBayar.setBackground(new java.awt.Color(218, 7, 7));
        btnBayar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setLabel("Bayar\t");
        btnBayar.setPreferredSize(new java.awt.Dimension(180, 50));
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 153, 0));
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setLabel("Tambah");
        btnTambah.setPreferredSize(new java.awt.Dimension(130, 55));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 214, 0));
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setLabel("Edit");
        btnEdit.setPreferredSize(new java.awt.Dimension(130, 55));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setLabel("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(130, 55));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("NAMA BARANG");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Total Harga :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Bayar :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("BARCODE BARANG");

        txtKodeBarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("HARGA BARANG");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("JUMLAH");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Kembalian :");

        cariBarang1.setBackground(new java.awt.Color(218, 7, 7));
        cariBarang1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cariBarang1.setForeground(new java.awt.Color(255, 255, 255));
        cariBarang1.setLabel("Cari Barang");
        cariBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBarang1ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        txtKembalian.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(752, 752, 752)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 583, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cariBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalHarga1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(txtBayar))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTotalHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addGap(605, 605, 605)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(883, 883, 883)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        btnLogout.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
 
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
            String Kembalian = txtKembalian.getText();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            if (model.getRowCount() == 0) { 
              JOptionPane.showMessageDialog(null, "Table kosong. Tambahkan barang terlebih dahulu.");
            } else if (Kembalian.isEmpty()){
               JOptionPane.showMessageDialog(null, "Masukkan total bayar!!!");
            } 
            else {
                JOptionPane.showMessageDialog(null, "Kembalian Anda: " + txtKembalian.getText());
                nomerNota++;
                updateLabelFaktur();
                txtTotalHarga.setText("0");
                txtTotalHarga1.setText("");
                txtBayar.setText("");
                txtKembalian.setText("");
                model.setRowCount(0);
            }
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
//        int KodeBarang = Integer.parseInt(txtKodeBarang.getText());
        Integer KodeBarang = Integer.valueOf(txtKodeBarang.getText());
        String NamaBarang = txtNamaBarang.getText();
        int HargaBarang = Integer.parseInt(txtHargaBarang.getText().replaceAll("Rp.", "").trim());
        Integer Jumlah = Integer.valueOf(txtJumlah.getText());
        int JumlahSementara = Jumlah * HargaBarang;
        if (KodeBarang <= 0){
            JOptionPane.showMessageDialog(null, "Barcode tidak boleh kosong");
        } else if (Jumlah <= 0){
            JOptionPane.showMessageDialog(null, "Jumlah tidak boleh kosong");
        } else{
            try{
        Connection conn = (Connection) Koneksi.koneksiDB();
        String sql = "SELECT * FROM barang WHERE barcode=? AND nama_barang=? AND harga=?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setInt(1, KodeBarang);
        ps.setString(2, NamaBarang);
        ps.setInt(3, HargaBarang);

        ResultSet rs = ps.executeQuery();
        boolean dataDitemukan = false;
        
        while(rs.next()){
            dataDitemukan = true;
            break;
        }

        if (dataDitemukan) {
            //Membuat Tabel Objek
            DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();

            boolean dataSudahAda = false;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                int kodeBarangTabel = Integer.parseInt(tbl.getValueAt(i, 0).toString());
                String namaBarangTabel = tbl.getValueAt(i, 1).toString();
                int hargaBarangTabel = Integer.parseInt(tbl.getValueAt(i, 3).toString().replaceAll("Rp.","").trim());
                
            if(KodeBarang.equals(kodeBarangTabel) && NamaBarang.equals(namaBarangTabel) && HargaBarang == hargaBarangTabel){
                // Data sudah ada, tambahkan jumlah ke dalam kolom jumlah yang sudah ada
                   int jumlahTabel = Integer.parseInt(tbl.getValueAt(i, 2).toString());
                   int totalHargaTabel = Integer.parseInt(tbl.getValueAt(i, 4).toString().substring(4));
                        
                   tbl.setValueAt(jumlahTabel + Jumlah, i, 2);
                   tbl.setValueAt("Rp. " + (totalHargaTabel + JumlahSementara), i, 4);
                   updateHargaTotal();
                   clearInputFields();
                   dataSudahAda = true;
                  break;
                }
            }
            if(!dataSudahAda){
             //membuat baris di tabel
                tbl.addRow(new Object[]{
                KodeBarang,
                NamaBarang,
                Jumlah,
                "Rp. " + HargaBarang,
                "Rp. " + JumlahSementara
            });

            int TotalHarga = 0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                TotalHarga += Integer.parseInt(tbl.getValueAt(i, 4).toString().substring(4));
            }

            txtTotalHarga.setText("Rp. " + TotalHarga);
            txtTotalHarga1.setText("Rp. " + TotalHarga);

            clearInputFields();
            
            } 
        } else {
            JOptionPane.showMessageDialog(null, "Data barang tidak ditemukan");
            }
         } 
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan dalam akses database");
        }
      } 
          
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        updateHargaTotal();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        String kodeBarang = jTable1.getValueAt(row, 0).toString();
        String NamaBarang = jTable1.getValueAt(row, 1).toString();
        String jumlah = jTable1.getValueAt(row, 2).toString();
        String harga = jTable1.getValueAt(row, 3).toString();
        String totalSementara = jTable1.getValueAt(row, 4).toString();
        
        txtKodeBarang.setText(kodeBarang);
        txtNamaBarang.setText(NamaBarang);
        txtJumlah.setText(jumlah);
        txtHargaBarang.setText(harga);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
       clearInputFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
        int row = jTable1.getSelectedRow();
        String kodeBarangStr = txtKodeBarang.getText();
        int kodeBarang = Integer.parseInt(kodeBarangStr);
        String NamaBarang = txtNamaBarang.getText();
        int jumlah = Integer.parseInt(txtJumlah.getText());
        int hargaBarang = Integer.parseInt(txtHargaBarang.getText().replaceAll("Rp.", "").trim());
        int totalHargaSementara = hargaBarang * jumlah;
        
        if(!isPriceSameInDb(kodeBarang, NamaBarang, hargaBarang)){
            JOptionPane.showMessageDialog(null, "Data tidak sesuai yang ada didatabase");
        }else if(jumlah <= 0){
            JOptionPane.showMessageDialog(null, "Jumlah tidak boleh kosong");
        }
        else{
        
        jTable1.setValueAt(kodeBarang, row, 0);
        jTable1.setValueAt(NamaBarang, row, 1);
        jTable1.setValueAt(jumlah, row, 2);
        jTable1.setValueAt("Rp. " +hargaBarang, row, 3);
        jTable1.setValueAt("Rp. " + totalHargaSementara, row, 4);

     
        int oldKodeBarang = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String oldNamaBarang = jTable1.getValueAt(row, 1).toString();
        int oldHargaBarang = Integer.parseInt(jTable1.getValueAt(row, 3).toString().replaceAll("Rp.", "").trim());
        
  
        // Membuat koneksi ke database
        Connection conn = (Connection) Koneksi.koneksiDB();
        String sql = "UPDATE barang SET barcode=?, nama_barang=?, harga=? WHERE barcode=? AND nama_barang=? AND harga=?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, kodeBarang);
            ps.setString(2, NamaBarang);
            ps.setInt(3, hargaBarang);
            ps.setInt(4, oldKodeBarang);
            ps.setString(5, oldNamaBarang);
            ps.setInt(6, oldHargaBarang);

            // Menjalankan pernyataan SQL untuk mengupdate data
            int result = ps.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data barang berhasil diupdate");
            
        }
        conn.close();
        updateHargaTotal();
        clearInputFields();
        }
    } catch (SQLException e) {
        e.printStackTrace();
        }  
    }//GEN-LAST:event_btnEditActionPerformed

    private boolean isPriceSameInDb(int kodeBarang, String namaBarang, int hargaBarang) throws SQLException{
    Connection conn = (Connection)Koneksi.koneksiDB();
    String sql = "SELECT * FROM barang WHERE BARCODE=? AND nama_barang=? AND harga=?";
        try(PreparedStatement ps = conn.prepareStatement(sql)){
               ps.setInt(1, kodeBarang);
               ps.setString(2, namaBarang);
               ps.setInt(3, hargaBarang);
               ResultSet rs = ps.executeQuery();
               return rs.next();
        } finally{
        conn.close();
        }
    }
    /**
     * Fungsi untuk memebersihkan fields
     */
     private void clearInputFields() {
            txtKodeBarang.setText("");
            txtNamaBarang.setText("");
            txtHargaBarang.setText("");
            txtJumlah.setText("");
            txtBayar.setText("");
            txtKembalian.setText("");
    }
     
    private void cariBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBarang1ActionPerformed
        // TODO add your handling code here:
        CariBarang cb = new CariBarang();
        cb.setVisible(true);
       
    }//GEN-LAST:event_cariBarang1ActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
    int result = JOptionPane.showConfirmDialog(null, "Apakah anda ingin logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
    if (result == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(null, "Logout Successful", "Logout", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }

    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Pilih baris yang akan dihapus");
    } else {
        int result = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus item ini dari tabel?", "Void Confirmation", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            try {
                // Mendapatkan indeks baris yang dipilih
                int row = jTable1.getSelectedRow();

                if (row != -1) {
                    DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
                    int totalHargaBaris = Integer.parseInt(tbl.getValueAt(row, 4).toString().substring(4));
                    int totalHarga = Integer.parseInt(txtTotalHarga.getText().substring(4)) - totalHargaBaris;
                    txtTotalHarga.setText("Rp. " + totalHarga);
                    txtTotalHarga1.setText("Rp. " + totalHarga);

                    tbl.removeRow(row);
                    updateHargaTotal();
                } 
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
  
    }//GEN-LAST:event_btnHapusActionPerformed
    
    private void updateHargaTotal(){
        int rowCount = jTable1.getRowCount();
        int TotalHarga = 0;
        
        for(int i = 0; i < rowCount; i++){
            String totalSementarastr = jTable1.getValueAt(i, 4).toString().replaceAll("Rp.", "").trim();
            int TotalSementara  = Integer.parseInt(totalSementarastr);
            TotalHarga += TotalSementara;
            
        }
        int diskon = (int) (0.01 * TotalHarga);
        int HargaDiskon = TotalHarga - diskon;
        
        
        int TotalHargaSetelah = Integer.parseInt(txtTotalHarga.getText().substring(4));
        
        TotalHargaSetelah = Integer.parseInt(txtTotalHarga1.getText().substring(4));
        txtTotalHarga.setText("Rp." + TotalHarga);
        txtTotalHarga1.setText("Rp. " + TotalHarga);
        int TotalBayar = Integer.parseInt(txtBayar.getText());
        int Kembalian = TotalBayar - TotalHarga;
            if(Kembalian < 0){
                    JOptionPane.showMessageDialog(null, "Pembayaran kurang!!");
            }else{
                    txtKembalian.setText("Rp. " + Kembalian);
                }
//        if(TotalHargaSetelah != TotalHarga){
//        updateHargaTotal();
//        }
        
    }
    
    public void setNamaKasir(String nama) {
        namaKasir.setText(nama);
    }
    
    private void updateNamaBarang() {
    String barcode = txtKodeBarang.getText();
    
    if (!barcode.isEmpty()) {
        try {
            Connection conn = (Connection) Koneksi.koneksiDB();
            String sql = "SELECT nama_barang, harga FROM barang WHERE barcode=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
                preparedStatement.setString(1, barcode);
                ResultSet rs = preparedStatement.executeQuery();
                    if (rs.next()) {
                        String namaBarang = rs.getString("nama_barang");
                        int hargaBarang = rs.getInt("harga");

                        txtNamaBarang.setText(namaBarang);
                        txtHargaBarang.setText("Rp. " + hargaBarang);
                    } else {
                        // Barcode tidak ditemukan, kosongkan nama_barang dan harga
                        txtNamaBarang.setText("");
                        txtHargaBarang.setText("");
                    }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    } 
}
    
/**
 * Pembuatan label faktur 
 */

  private int nomerNota = 1;
    private void updateLabelFaktur() {
    String kodeToko = "V708";
    String tanggalPembelian = getFormattedDate();
    String nomerNotaStr = String.format("%04d", nomerNota);
    String fakturText = String.format("%s - %s - %s", kodeToko, tanggalPembelian, nomerNotaStr);
    faktur.setText(fakturText);  
}

    private String getFormattedDate(){
    Date date = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("ddMMyyyy");
    return dateFormat.format(date);
}
    
 /**
  * Menambahkan fungsi di kelas CariBarang
  * @return 
  */
    public javax.swing.JTable getJTable() {
        return jTable1;
    }
    
  
   public JTextField getTxtKodeBarang() {
    return txtKodeBarang;
}
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainApp mainApp = new MainApp();
                mainApp.setVisible(true);
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBayar;
    private java.awt.Button btnClear;
    private java.awt.Button btnEdit;
    private java.awt.Button btnHapus;
    private java.awt.Button btnLogout;
    private java.awt.Button btnTambah;
    private java.awt.Button btnTransaksi;
    private java.awt.Button cariBarang1;
    private javax.swing.JLabel faktur;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel namaKasir;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JLabel txtKembalian;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JLabel txtTotalHarga;
    private javax.swing.JTextField txtTotalHarga1;
    // End of variables declaration//GEN-END:variables
}
